//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class storesEntities1 : DbContext
    {
        public storesEntities1()
            : base("name=storesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Advertisement> Advertisements { get; set; }
        public virtual DbSet<AdvertisementsKind> AdvertisementsKinds { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Cloth> Clothes { get; set; }
        public virtual DbSet<Company> Companys { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
    }
}
