//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int SubjectID { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> DatetimeOfWriting { get; set; }
        public Nullable<bool> IfWantUpdate { get; set; }
        public Nullable<System.DateTime> GotLastAnswer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
        public virtual Store Store { get; set; }
    }
}
