//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisements
    {
        public int AdvertisementID { get; set; }
        public string pictureURL { get; set; }
        public Nullable<int> KindID { get; set; }
        public int CompanyID { get; set; }
        public string DescribeAd { get; set; }
    
        public virtual Companys Companys { get; set; }
        public virtual AdvertisementsKinds AdvertisementsKinds { get; set; }
    }
}
