//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bills
    {
        public int BillID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string BillPath { get; set; }
        public Nullable<System.DateTime> BilDate { get; set; }
    
        public virtual Stores Stores { get; set; }
    }
}
