//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class storesEntities1 : DbContext
    {
        public storesEntities1()
            : base("name=storesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Advertisements> Advertisements { get; set; }
        public virtual DbSet<AdvertisementsKinds> AdvertisementsKinds { get; set; }
        public virtual DbSet<Bills> Bills { get; set; }
        public virtual DbSet<Clothes> Clothes { get; set; }
        public virtual DbSet<Companys> Companys { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Stores> Stores { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
    }
}
